
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pdp_table
    username: postgres
    password: 2006
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8081

jwt:
  expiry: 300000
  secret: gjhkoiutrefdsavzbxcnmktjyhretgwedfvbnjkrjyerhsfg